version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: project_backend
    ports:
      - "8080:8000"
    networks:
      - backend-network
      - common-network
    secrets:
      - db-password
    environment:
      DB_HOST: database
      DB_PASSWORD_FILE: /run/secrets/db-password
    depends_on:
      - database 

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: project_proxy
    ports:
      - "443:443"
    depends_on:
      - backend
    networks:
      - proxy-network
      - common-network
    volumes:
      - ./proxy/ssl:/etc/nginx/ssl

  database:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    networks:
      - backend-network
      - common-network

secrets:
  db-password:
    file: ./secrets/db-password

networks:
  backend-network:
    driver: bridge
  proxy-network:
    driver: bridge
  common-network:
    driver: bridge
